package org.project.manage.util;

import java.util.HashMap;
import java.util.Map;


public class ContentType {
    public static final String MIME_APPLICATION_ANDREW_INSET = "application/andrew-inset";
    public static final String MIME_APPLICATION_JSON = "application/json";
    public static final String MIME_APPLICATION_ZIP = "application/zip";
    public static final String MIME_APPLICATION_X_GZIP = "application/x-gzip";
    public static final String MIME_APPLICATION_TGZ = "application/tgz";
    public static final String MIME_APPLICATION_MSWORD = "application/msword";
    public static final String MIME_APPLICATION_MSWORD_2007 = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    public static final String MIME_APPLICATION_VND_TEXT = "application/vnd.oasis.opendocument.text";
    public static final String MIME_APPLICATION_POSTSCRIPT = "application/postscript";
    public static final String MIME_APPLICATION_PDF = "application/pdf";
    public static final String MIME_APPLICATION_JNLP = "application/jnlp";
    public static final String MIME_APPLICATION_MAC_BINHEX40 = "application/mac-binhex40";
    public static final String MIME_APPLICATION_MAC_COMPACTPRO = "application/mac-compactpro";
    public static final String MIME_APPLICATION_MATHML_XML = "application/mathml+xml";
    public static final String MIME_APPLICATION_OCTET_STREAM = "application/octet-stream";
    public static final String MIME_APPLICATION_ODA = "application/oda";
    public static final String MIME_APPLICATION_RDF_XML = "application/rdf+xml";
    public static final String MIME_APPLICATION_JAVA_ARCHIVE = "application/java-archive";
    public static final String MIME_APPLICATION_RDF_SMIL = "application/smil";
    public static final String MIME_APPLICATION_SRGS = "application/srgs";
    public static final String MIME_APPLICATION_SRGS_XML = "application/srgs+xml";
    public static final String MIME_APPLICATION_VND_MIF = "application/vnd.mif";
    public static final String MIME_APPLICATION_VND_MSEXCEL = "application/vnd.ms-excel";
    public static final String MIME_APPLICATION_TIKA_MSEXCEL = "application/x-tika-ooxml";
    public static final String MIME_APPLICATION_VND_MSEXCEL_2007 = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    public static final String MIME_APPLICATION_VND_SPREADSHEET = "application/vnd.oasis.opendocument.spreadsheet";
    public static final String MIME_APPLICATION_VND_MSPOWERPOINT = "application/vnd.ms-powerpoint";
    public static final String MIME_APPLICATION_VND_RNREALMEDIA = "application/vnd.rn-realmedia";
    public static final String MIME_APPLICATION_X_BCPIO = "application/x-bcpio";
    public static final String MIME_APPLICATION_X_CDLINK = "application/x-cdlink";
    public static final String MIME_APPLICATION_X_CHESS_PGN = "application/x-chess-pgn";
    public static final String MIME_APPLICATION_X_CPIO = "application/x-cpio";
    public static final String MIME_APPLICATION_X_CSH = "application/x-csh";
    public static final String MIME_APPLICATION_X_DIRECTOR = "application/x-director";
    public static final String MIME_APPLICATION_X_DVI = "application/x-dvi";
    public static final String MIME_APPLICATION_X_FUTURESPLASH = "application/x-futuresplash";
    public static final String MIME_APPLICATION_X_GTAR = "application/x-gtar";
    public static final String MIME_APPLICATION_X_HDF = "application/x-hdf";
    public static final String MIME_APPLICATION_X_JAVASCRIPT = "application/x-javascript";
    public static final String MIME_APPLICATION_X_KOAN = "application/x-koan";
    public static final String MIME_APPLICATION_X_LATEX = "application/x-latex";
    public static final String MIME_APPLICATION_X_NETCDF = "application/x-netcdf";
    public static final String MIME_APPLICATION_X_OGG = "application/x-ogg";
    public static final String MIME_APPLICATION_X_SH = "application/x-sh";
    public static final String MIME_APPLICATION_X_SHAR = "application/x-shar";
    public static final String MIME_APPLICATION_X_SHOCKWAVE_FLASH = "application/x-shockwave-flash";
    public static final String MIME_APPLICATION_X_STUFFIT = "application/x-stuffit";
    public static final String MIME_APPLICATION_X_SV4CPIO = "application/x-sv4cpio";
    public static final String MIME_APPLICATION_X_SV4CRC = "application/x-sv4crc";
    public static final String MIME_APPLICATION_X_TAR = "application/x-tar";
    public static final String MIME_APPLICATION_X_RAR_COMPRESSED = "application/x-rar-compressed";
    public static final String MIME_APPLICATION_X_TCL = "application/x-tcl";
    public static final String MIME_APPLICATION_X_TEX = "application/x-tex";
    public static final String MIME_APPLICATION_X_TEXINFO = "application/x-texinfo";
    public static final String MIME_APPLICATION_X_TROFF = "application/x-troff";
    public static final String MIME_APPLICATION_X_TROFF_MAN = "application/x-troff-man";
    public static final String MIME_APPLICATION_X_TROFF_ME = "application/x-troff-me";
    public static final String MIME_APPLICATION_X_TROFF_MS = "application/x-troff-ms";
    public static final String MIME_APPLICATION_X_USTAR = "application/x-ustar";
    public static final String MIME_APPLICATION_X_WAIS_SOURCE = "application/x-wais-source";
    public static final String MIME_APPLICATION_VND_MOZZILLA_XUL_XML = "application/vnd.mozilla.xul+xml";
    public static final String MIME_APPLICATION_XHTML_XML = "application/xhtml+xml";
    public static final String MIME_APPLICATION_XSLT_XML = "application/xslt+xml";
    public static final String MIME_APPLICATION_XML = "application/xml";
    public static final String MIME_APPLICATION_XML_DTD = "application/xml-dtd";
    public static final String MIME_IMAGE_BMP = "image/bmp";
    public static final String MIME_IMAGE_CGM = "image/cgm";
    public static final String MIME_IMAGE_GIF = "image/gif";
    public static final String MIME_IMAGE_IEF = "image/ief";
    public static final String MIME_IMAGE_JPEG = "image/jpeg";
    public static final String MIME_IMAGE_TIFF = "image/tiff";
    public static final String MIME_IMAGE_PNG = "image/png";
    public static final String MIME_IMAGE_SVG_XML = "image/svg+xml";
    public static final String MIME_IMAGE_VND_DJVU = "image/vnd.djvu";
    public static final String MIME_IMAGE_WAP_WBMP = "image/vnd.wap.wbmp";
    public static final String MIME_IMAGE_X_CMU_RASTER = "image/x-cmu-raster";
    public static final String MIME_IMAGE_X_ICON = "image/x-icon";
    public static final String MIME_IMAGE_X_PORTABLE_ANYMAP = "image/x-portable-anymap";
    public static final String MIME_IMAGE_X_PORTABLE_BITMAP = "image/x-portable-bitmap";
    public static final String MIME_IMAGE_X_PORTABLE_GRAYMAP = "image/x-portable-graymap";
    public static final String MIME_IMAGE_X_PORTABLE_PIXMAP = "image/x-portable-pixmap";
    public static final String MIME_IMAGE_X_RGB = "image/x-rgb";
    public static final String MIME_AUDIO_BASIC = "audio/basic";
    public static final String MIME_AUDIO_MIDI = "audio/midi";
    public static final String MIME_AUDIO_MPEG = "audio/mpeg";
    public static final String MIME_AUDIO_X_AIFF = "audio/x-aiff";
    public static final String MIME_AUDIO_X_MPEGURL = "audio/x-mpegurl";
    public static final String MIME_AUDIO_X_PN_REALAUDIO = "audio/x-pn-realaudio";
    public static final String MIME_AUDIO_X_WAV = "audio/x-wav";
    public static final String MIME_CHEMICAL_X_PDB = "chemical/x-pdb";
    public static final String MIME_CHEMICAL_X_XYZ = "chemical/x-xyz";
    public static final String MIME_MODEL_IGES = "model/iges";
    public static final String MIME_MODEL_MESH = "model/mesh";
    public static final String MIME_MODEL_VRLM = "model/vrml";
    public static final String MIME_TEXT_PLAIN = "text/plain";
    public static final String MIME_TEXT_RICHTEXT = "text/richtext";
    public static final String MIME_TEXT_RTF = "text/rtf";
    public static final String MIME_TEXT_HTML = "text/html";
    public static final String MIME_TEXT_CALENDAR = "text/calendar";
    public static final String MIME_TEXT_CSS = "text/css";
    public static final String MIME_TEXT_SGML = "text/sgml";
    public static final String MIME_TEXT_TAB_SEPARATED_VALUES = "text/tab-separated-values";
    public static final String MIME_TEXT_VND_WAP_XML = "text/vnd.wap.wml";
    public static final String MIME_TEXT_VND_WAP_WMLSCRIPT = "text/vnd.wap.wmlscript";
    public static final String MIME_TEXT_X_SETEXT = "text/x-setext";
    public static final String MIME_TEXT_X_COMPONENT = "text/x-component";
    public static final String MIME_VIDEO_QUICKTIME = "video/quicktime";
    public static final String MIME_VIDEO_MPEG = "video/mpeg";
    public static final String MIME_VIDEO_VND_MPEGURL = "video/vnd.mpegurl";
    public static final String MIME_VIDEO_X_MSVIDEO = "video/x-msvideo";
    public static final String MIME_VIDEO_X_MS_WMV = "video/x-ms-wmv";
    public static final String MIME_VIDEO_X_SGI_MOVIE = "video/x-sgi-movie";
    public static final String MIME_X_CONFERENCE_X_COOLTALK = "x-conference/x-cooltalk";

    public static String getExtension(String key) {
        Map<String, String> contentTypes = new HashMap<String, String>();
        contentTypes.put(MIME_APPLICATION_VND_MOZZILLA_XUL_XML, "xul");
        contentTypes.put(MIME_APPLICATION_JSON, "json");
        contentTypes.put(MIME_X_CONFERENCE_X_COOLTALK, "ice");
        contentTypes.put(MIME_VIDEO_X_SGI_MOVIE, "movie");
        contentTypes.put(MIME_VIDEO_X_MSVIDEO, "avi");
        contentTypes.put(MIME_VIDEO_X_MS_WMV, "wmv");
        contentTypes.put(MIME_VIDEO_VND_MPEGURL, "m4u");
        contentTypes.put(MIME_TEXT_X_COMPONENT, "htc");
        contentTypes.put(MIME_TEXT_X_SETEXT, "etx");
        contentTypes.put(MIME_TEXT_VND_WAP_WMLSCRIPT, "wmls");
        contentTypes.put(MIME_TEXT_VND_WAP_XML, "wml");
        contentTypes.put(MIME_TEXT_TAB_SEPARATED_VALUES, "tsv");
        contentTypes.put(MIME_TEXT_SGML, "sgml");
        contentTypes.put(MIME_TEXT_CSS, "css");
        contentTypes.put(MIME_TEXT_CALENDAR, "ics");
        contentTypes.put(MIME_MODEL_VRLM, "vrlm");
        contentTypes.put(MIME_MODEL_MESH, "mesh");
        contentTypes.put(MIME_MODEL_IGES, "iges");
        contentTypes.put(MIME_IMAGE_X_RGB, "rgb");
        contentTypes.put(MIME_IMAGE_X_PORTABLE_PIXMAP, "ppm");
        contentTypes.put(MIME_IMAGE_X_PORTABLE_GRAYMAP, "pgm");
        contentTypes.put(MIME_IMAGE_X_PORTABLE_BITMAP, "pbm");
        contentTypes.put(MIME_IMAGE_X_PORTABLE_ANYMAP, "pnm");
        contentTypes.put(MIME_IMAGE_X_ICON, "ico");
        contentTypes.put(MIME_IMAGE_X_CMU_RASTER, "ras");
        contentTypes.put(MIME_IMAGE_WAP_WBMP, "wbmp");
        contentTypes.put(MIME_IMAGE_VND_DJVU, "djvu");
        contentTypes.put(MIME_IMAGE_SVG_XML, "svg");
        contentTypes.put(MIME_IMAGE_IEF, "ief");
        contentTypes.put(MIME_IMAGE_CGM, "cgm");
        contentTypes.put(MIME_IMAGE_BMP, "bmp");
        contentTypes.put(MIME_CHEMICAL_X_XYZ, "xyz");
        contentTypes.put(MIME_CHEMICAL_X_PDB, "pdb");
        contentTypes.put(MIME_AUDIO_X_PN_REALAUDIO, "ra");
        contentTypes.put(MIME_AUDIO_X_MPEGURL, "m3u");
        contentTypes.put(MIME_AUDIO_X_AIFF, "aiff");
        contentTypes.put(MIME_AUDIO_MPEG, "mp3");
        contentTypes.put(MIME_AUDIO_MIDI, "midi");
        contentTypes.put(MIME_APPLICATION_XML_DTD, "dtd");
        contentTypes.put(MIME_APPLICATION_XML, "xml");
        contentTypes.put(MIME_APPLICATION_XSLT_XML, "xslt");
        contentTypes.put(MIME_APPLICATION_XHTML_XML, "xhtml");
        contentTypes.put(MIME_APPLICATION_X_WAIS_SOURCE, "src");
        contentTypes.put(MIME_APPLICATION_X_USTAR, "ustar");
        contentTypes.put(MIME_APPLICATION_X_TROFF_MS, "ms");
        contentTypes.put(MIME_APPLICATION_X_TROFF_ME, "me");
        contentTypes.put(MIME_APPLICATION_X_TROFF_MAN, "man");
        contentTypes.put(MIME_APPLICATION_X_TROFF, "roff");
        contentTypes.put(MIME_APPLICATION_X_TEXINFO, "texi");
        contentTypes.put(MIME_APPLICATION_X_TEX, "tex");
        contentTypes.put(MIME_APPLICATION_X_TCL, "tcl");
        contentTypes.put(MIME_APPLICATION_X_SV4CRC, "sv4crc");
        contentTypes.put(MIME_APPLICATION_X_SV4CPIO, "sv4cpio");
        contentTypes.put(MIME_APPLICATION_X_STUFFIT, "sit");
        contentTypes.put(MIME_APPLICATION_X_SHOCKWAVE_FLASH, "swf");
        contentTypes.put(MIME_APPLICATION_X_SHAR, "shar");
        contentTypes.put(MIME_APPLICATION_X_SH, "sh");
        contentTypes.put(MIME_APPLICATION_X_NETCDF, "cdf");
        contentTypes.put(MIME_APPLICATION_X_LATEX, "latex");
        contentTypes.put(MIME_APPLICATION_X_KOAN, "skm");
        contentTypes.put(MIME_APPLICATION_X_JAVASCRIPT, "js");
        contentTypes.put(MIME_APPLICATION_X_HDF, "hdf");
        contentTypes.put(MIME_APPLICATION_X_GTAR, "gtar");
        contentTypes.put(MIME_APPLICATION_X_FUTURESPLASH, "spl");
        contentTypes.put(MIME_APPLICATION_X_DVI, "dvi");
        contentTypes.put(MIME_APPLICATION_X_DIRECTOR, "dir");
        contentTypes.put(MIME_APPLICATION_X_CSH, "csh");
        contentTypes.put(MIME_APPLICATION_X_CPIO, "cpio");
        contentTypes.put(MIME_APPLICATION_X_CHESS_PGN, "pgn");
        contentTypes.put(MIME_APPLICATION_X_CDLINK, "vcd");
        contentTypes.put(MIME_APPLICATION_X_BCPIO, "bcpio");
        contentTypes.put(MIME_APPLICATION_VND_RNREALMEDIA, "rm");
        contentTypes.put(MIME_APPLICATION_VND_MSPOWERPOINT, "ppt");
        contentTypes.put(MIME_APPLICATION_VND_MIF, "mif");
        contentTypes.put(MIME_APPLICATION_SRGS_XML, "grxml");
        contentTypes.put(MIME_APPLICATION_SRGS, "gram");
        contentTypes.put(MIME_APPLICATION_RDF_SMIL, "smil");
        contentTypes.put(MIME_APPLICATION_RDF_XML, "rdf");
        contentTypes.put(MIME_APPLICATION_X_OGG, "ogg");
        contentTypes.put(MIME_APPLICATION_ODA, "oda");
        contentTypes.put(MIME_APPLICATION_MATHML_XML, "mathml");
        contentTypes.put(MIME_APPLICATION_MAC_COMPACTPRO, "cpt");
        contentTypes.put(MIME_APPLICATION_MAC_BINHEX40, "hqx");
        contentTypes.put(MIME_APPLICATION_JNLP, "jnlp");
        contentTypes.put(MIME_APPLICATION_ANDREW_INSET, "ez");
        contentTypes.put(MIME_TEXT_PLAIN, "txt");
        contentTypes.put(MIME_TEXT_RTF, "rtf");
        contentTypes.put(MIME_TEXT_RICHTEXT, "rtx");
        contentTypes.put(MIME_TEXT_HTML, "html");
        contentTypes.put(MIME_APPLICATION_ZIP, "zip");
        contentTypes.put(MIME_APPLICATION_X_RAR_COMPRESSED, "rar");
        contentTypes.put(MIME_APPLICATION_X_GZIP, "gzip");
        contentTypes.put(MIME_APPLICATION_TGZ, "tgz");
        contentTypes.put(MIME_APPLICATION_X_TAR, "tar");
        contentTypes.put(MIME_IMAGE_GIF, "gif");
        contentTypes.put(MIME_IMAGE_JPEG, "jpg");
        contentTypes.put(MIME_IMAGE_TIFF, "tiff");
        contentTypes.put(MIME_IMAGE_PNG, "png");
        contentTypes.put(MIME_AUDIO_BASIC, "au");
        contentTypes.put(MIME_AUDIO_X_WAV, "wav");
        contentTypes.put(MIME_VIDEO_QUICKTIME, "mov");
        contentTypes.put(MIME_VIDEO_MPEG, "mpg");
        contentTypes.put(MIME_APPLICATION_MSWORD, "doc");
        contentTypes.put(MIME_APPLICATION_MSWORD_2007, "docx");
        contentTypes.put(MIME_APPLICATION_VND_TEXT, "odt");
        contentTypes.put(MIME_APPLICATION_VND_MSEXCEL, "xls");
        contentTypes.put(MIME_APPLICATION_VND_MSEXCEL_2007, "xlsx");
        contentTypes.put(MIME_APPLICATION_TIKA_MSEXCEL, "xlsx");
        contentTypes.put(MIME_APPLICATION_VND_SPREADSHEET, "ods");
        contentTypes.put(MIME_APPLICATION_POSTSCRIPT, "ps");
        contentTypes.put(MIME_APPLICATION_PDF, "pdf");
        contentTypes.put(MIME_APPLICATION_OCTET_STREAM, "exe");
        contentTypes.put(MIME_APPLICATION_JAVA_ARCHIVE, "jar");
        return contentTypes.get(key);
    }

    public static String getMineType(String key) {
        Map<String, String> contentTypes = new HashMap<String, String>();
        contentTypes.put("xul", MIME_APPLICATION_VND_MOZZILLA_XUL_XML);
        contentTypes.put("json", MIME_APPLICATION_JSON);
        contentTypes.put("ice", MIME_X_CONFERENCE_X_COOLTALK);
        contentTypes.put("movie", MIME_VIDEO_X_SGI_MOVIE);
        contentTypes.put("avi", MIME_VIDEO_X_MSVIDEO);
        contentTypes.put("wmv", MIME_VIDEO_X_MS_WMV);
        contentTypes.put("m4u", MIME_VIDEO_VND_MPEGURL);
        contentTypes.put("htc", MIME_TEXT_X_COMPONENT);
        contentTypes.put("etx", MIME_TEXT_X_SETEXT);
        contentTypes.put("wmls", MIME_TEXT_VND_WAP_WMLSCRIPT);
        contentTypes.put("wml", MIME_TEXT_VND_WAP_XML);
        contentTypes.put("tsv", MIME_TEXT_TAB_SEPARATED_VALUES);
        contentTypes.put("sgml", MIME_TEXT_SGML);
        contentTypes.put("css", MIME_TEXT_CSS);
        contentTypes.put("ics", MIME_TEXT_CALENDAR);
        contentTypes.put("vrlm", MIME_MODEL_VRLM);
        contentTypes.put("mesh", MIME_MODEL_MESH);
        contentTypes.put("iges", MIME_MODEL_IGES);
        contentTypes.put("rgb", MIME_IMAGE_X_RGB);
        contentTypes.put("ppm", MIME_IMAGE_X_PORTABLE_PIXMAP);
        contentTypes.put("pgm", MIME_IMAGE_X_PORTABLE_GRAYMAP);
        contentTypes.put("pbm", MIME_IMAGE_X_PORTABLE_BITMAP);
        contentTypes.put("pnm", MIME_IMAGE_X_PORTABLE_ANYMAP);
        contentTypes.put("ico", MIME_IMAGE_X_ICON);
        contentTypes.put("ras", MIME_IMAGE_X_CMU_RASTER);
        contentTypes.put("wbmp", MIME_IMAGE_WAP_WBMP);
        contentTypes.put("djvu", MIME_IMAGE_VND_DJVU);
        contentTypes.put("svg", MIME_IMAGE_SVG_XML);
        contentTypes.put("ief", MIME_IMAGE_IEF);
        contentTypes.put("cgm", MIME_IMAGE_CGM);
        contentTypes.put("bmp", MIME_IMAGE_BMP);
        contentTypes.put("xyz", MIME_CHEMICAL_X_XYZ);
        contentTypes.put("pdb", MIME_CHEMICAL_X_PDB);
        contentTypes.put("ra", MIME_AUDIO_X_PN_REALAUDIO);
        contentTypes.put("m3u", MIME_AUDIO_X_MPEGURL);
        contentTypes.put("aiff", MIME_AUDIO_X_AIFF);
        contentTypes.put("mp3", MIME_AUDIO_MPEG);
        contentTypes.put("midi", MIME_AUDIO_MIDI);
        contentTypes.put("dtd", MIME_APPLICATION_XML_DTD);
        contentTypes.put("xml", MIME_APPLICATION_XML);
        contentTypes.put("xslt", MIME_APPLICATION_XSLT_XML);
        contentTypes.put("xhtml", MIME_APPLICATION_XHTML_XML);
        contentTypes.put("src", MIME_APPLICATION_X_WAIS_SOURCE);
        contentTypes.put("ustar", MIME_APPLICATION_X_USTAR);
        contentTypes.put("ms", MIME_APPLICATION_X_TROFF_MS);
        contentTypes.put("me", MIME_APPLICATION_X_TROFF_ME);
        contentTypes.put("man", MIME_APPLICATION_X_TROFF_MAN);
        contentTypes.put("roff", MIME_APPLICATION_X_TROFF);
        contentTypes.put("texi", MIME_APPLICATION_X_TEXINFO);
        contentTypes.put("tex", MIME_APPLICATION_X_TEX);
        contentTypes.put("tcl", MIME_APPLICATION_X_TCL);
        contentTypes.put("sv4crc", MIME_APPLICATION_X_SV4CRC);
        contentTypes.put("sv4cpio", MIME_APPLICATION_X_SV4CPIO);
        contentTypes.put("sit", MIME_APPLICATION_X_STUFFIT);
        contentTypes.put("swf", MIME_APPLICATION_X_SHOCKWAVE_FLASH);
        contentTypes.put("shar", MIME_APPLICATION_X_SHAR);
        contentTypes.put("sh", MIME_APPLICATION_X_SH);
        contentTypes.put("cdf", MIME_APPLICATION_X_NETCDF);
        contentTypes.put("latex", MIME_APPLICATION_X_LATEX);
        contentTypes.put("skm", MIME_APPLICATION_X_KOAN);
        contentTypes.put("js", MIME_APPLICATION_X_JAVASCRIPT);
        contentTypes.put("hdf", MIME_APPLICATION_X_HDF);
        contentTypes.put("gtar", MIME_APPLICATION_X_GTAR);
        contentTypes.put("spl", MIME_APPLICATION_X_FUTURESPLASH);
        contentTypes.put("dvi", MIME_APPLICATION_X_DVI);
        contentTypes.put("dir", MIME_APPLICATION_X_DIRECTOR);
        contentTypes.put("csh", MIME_APPLICATION_X_CSH);
        contentTypes.put("cpio", MIME_APPLICATION_X_CPIO);
        contentTypes.put("pgn", MIME_APPLICATION_X_CHESS_PGN);
        contentTypes.put("vcd", MIME_APPLICATION_X_CDLINK);
        contentTypes.put("bcpio", MIME_APPLICATION_X_BCPIO);
        contentTypes.put("rm", MIME_APPLICATION_VND_RNREALMEDIA);
        contentTypes.put("ppt", MIME_APPLICATION_VND_MSPOWERPOINT);
        contentTypes.put("mif", MIME_APPLICATION_VND_MIF);
        contentTypes.put("grxml", MIME_APPLICATION_SRGS_XML);
        contentTypes.put("gram", MIME_APPLICATION_SRGS);
        contentTypes.put("smil", MIME_APPLICATION_RDF_SMIL);
        contentTypes.put("rdf", MIME_APPLICATION_RDF_XML);
        contentTypes.put("ogg", MIME_APPLICATION_X_OGG);
        contentTypes.put("oda", MIME_APPLICATION_ODA);
        contentTypes.put("mathml", MIME_APPLICATION_MATHML_XML);
        contentTypes.put("cpt", MIME_APPLICATION_MAC_COMPACTPRO);
        contentTypes.put("hqx", MIME_APPLICATION_MAC_BINHEX40);
        contentTypes.put("jnlp", MIME_APPLICATION_JNLP);
        contentTypes.put("ez", MIME_APPLICATION_ANDREW_INSET);
        contentTypes.put("txt", MIME_TEXT_PLAIN);
        contentTypes.put("rtf", MIME_TEXT_RTF);
        contentTypes.put("rtx", MIME_TEXT_RICHTEXT);
        contentTypes.put("html", MIME_TEXT_HTML);
        contentTypes.put("zip", MIME_APPLICATION_ZIP);
        contentTypes.put("rar", MIME_APPLICATION_X_RAR_COMPRESSED);
        contentTypes.put("gzip", MIME_APPLICATION_X_GZIP);
        contentTypes.put("tgz", MIME_APPLICATION_TGZ);
        contentTypes.put("tar", MIME_APPLICATION_X_TAR);
        contentTypes.put("gif", MIME_IMAGE_GIF);
        contentTypes.put("jpg", MIME_IMAGE_JPEG);
        contentTypes.put("jpeg", MIME_IMAGE_JPEG);
        contentTypes.put("tiff", MIME_IMAGE_TIFF);
        contentTypes.put("png", MIME_IMAGE_PNG);
        contentTypes.put("au", MIME_AUDIO_BASIC);
        contentTypes.put("wav", MIME_AUDIO_X_WAV);
        contentTypes.put("mov", MIME_VIDEO_QUICKTIME);
        contentTypes.put("mpg", MIME_VIDEO_MPEG);
        contentTypes.put("doc", MIME_APPLICATION_MSWORD);
        contentTypes.put("docx", MIME_APPLICATION_MSWORD_2007);
        contentTypes.put("odt", MIME_APPLICATION_VND_TEXT);
        contentTypes.put("xls", MIME_APPLICATION_VND_MSEXCEL);
        contentTypes.put("xlsx", MIME_APPLICATION_VND_MSEXCEL_2007);
        contentTypes.put("ods", MIME_APPLICATION_VND_SPREADSHEET);
        contentTypes.put("ps", MIME_APPLICATION_POSTSCRIPT);
        contentTypes.put("pdf", MIME_APPLICATION_PDF);
        contentTypes.put("exe", MIME_APPLICATION_OCTET_STREAM);
        contentTypes.put("jar", MIME_APPLICATION_JAVA_ARCHIVE);
        return contentTypes.get(key);
    }
}
